### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by YuryVezhyk** [JohnnieLi/ngx-social-button#2]
I have this error in console: 

"The method FB.getLoginStatus can no longer be called from http pages. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/"

But facebook login/logout works good.

**Comment by JohnnieLi** [comment]
Hi, This is actually a kind of warning, since Facebook changed the policy which requires 'https' to support API calls. the testing in localhost without https will show this warning. It won't affect the function and the error will be gone when your site has 'https' SSL certificate
